# Generated by Django 3.1.2 on 2020-10-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_decsription',
            new_name='image_description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
